(function registerComponents() {
  window.BugGenie = window.BugGenie || {};

  const { html } = window.BugGenie;

  const resolveLucideIcon = (name) => {
    const names = Array.isArray(name) ? name : [name];

    for (const iconName of names) {
      if (window.lucide?.icons?.[iconName]) {
        return window.lucide.icons[iconName];
      }
    }

    return null;
  };

  const LucideIcon = ({ name, className = "", size, strokeWidth = 2, fallback = "" }) => {
    const icon = resolveLucideIcon(name);

    if (!icon) {
      return fallback ? html`<span className=${className} style=${size ? { fontSize: size * 0.8 } : undefined}>${fallback}</span>` : null;
    }

    const style = size ? { width: size, height: size } : undefined;

    return html`
      <span
        className=${`inline-flex shrink-0 ${className}`.trim()}
        style=${style}
        aria-hidden="true"
        dangerouslySetInnerHTML=${{
          __html: icon.toSvg({
            width: "100%",
            height: "100%",
            class: "w-full h-full",
            strokeWidth
          })
        }}
      />
    `;
  };

  const InputGroup = ({ label, value, placeholder, onChange }) => {
    return html`
      <div>
        <label className="text-[10px] font-bold text-slate-400 uppercase block mb-1">
          ${label}
        </label>
        <input
          type="text"
          placeholder=${placeholder}
          value=${value}
          onChange=${(event) => onChange(event.target.value)}
          className="w-full bg-slate-50 border border-slate-200 rounded-lg px-3 py-2 text-sm"
        />
      </div>
    `;
  };

  const StatusCard = ({ title, content, type }) => {
    const toneClasses =
      type === "success"
        ? "bg-green-50 border-green-100 text-green-800"
        : "bg-red-50 border-red-100 text-red-800";

    return html`
      <div className=${`p-4 rounded-xl border ${toneClasses}`}>
        <h5 className="text-[10px] font-bold uppercase mb-2 opacity-60">
          ${title} Outcome
        </h5>
        <p className="text-sm leading-relaxed">${content || "---"}</p>
      </div>
    `;
  };

  const DataRow = ({ label, value }) => {
    return html`
      <div className="flex border-b border-slate-100 last:border-0 py-2">
        <div className="w-1/3 text-xs font-bold text-slate-500 uppercase shrink-0">
          ${label}
        </div>
        <div className="w-2/3 text-sm font-medium text-slate-900">${value}</div>
      </div>
    `;
  };

  class ErrorBoundary extends React.Component {
    constructor(props) {
      super(props);
      this.state = { hasError: false };
    }

    static getDerivedStateFromError() {
      return { hasError: true };
    }

    render() {
      if (this.state.hasError) {
        return html`
          <div className="bg-red-50 border border-red-200 rounded-xl p-8 text-center">
            <${LucideIcon}
              name=${["circle-alert", "alert-circle", "triangle-alert"]}
              className="text-red-500 w-12 h-12 mx-auto mb-3"
            />
            <h3 className="text-lg font-bold text-red-700">Something went wrong</h3>
            <p className="text-red-600 mt-2">
              We couldn't display the report. Please try generating again.
            </p>
          </div>
        `;
      }

      return this.props.children;
    }
  }

  const ReportDisplay = ({ report, files }) => {
    if (!report) {
      return null;
    }

    const r = report;
    const sys = r.systemContext || {};
    const hasImageFiles = files.some((file) => file.type === "image");
    const severityClass =
      r.metadata?.severity === "Critical"
        ? "bg-red-600"
        : r.metadata?.severity === "High"
          ? "bg-orange-500"
          : "bg-amber-500";

    return html`
      <div
        className="bg-white shadow-lg border border-slate-200 mx-auto"
        style=${{ padding: "40px", maxWidth: "850px" }}
      >
        <div className="border-b-4 border-slate-900 pb-6 mb-8 flex justify-between items-end">
          <div>
            <h1 className="text-3xl font-black uppercase tracking-tight text-slate-900 mb-1">
              Bug Report
            </h1>
            <p className="text-slate-500 font-medium">Generated by BugGenie AI</p>
          </div>
          <div className="text-right">
            <div className="text-2xl font-bold text-indigo-600">${sys.bugId ?? "N/A"}</div>
            <div className="text-sm font-semibold text-slate-400">
              ${sys.dateReported ?? "N/A"}
            </div>
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mb-8">
          <section>
            <h2 className="text-sm font-bold bg-slate-100 px-3 py-1 mb-3 uppercase tracking-widest text-slate-700 border-l-4 border-indigo-500">
              [1] Metadata
            </h2>
            <div className="space-y-1 pl-1">
              <${DataRow} label="Title" value=${r.metadata?.title ?? "N/A"} />
              <div className="flex border-b border-slate-100 py-2">
                <div className="w-1/3 text-xs font-bold text-slate-500 uppercase shrink-0">
                  Severity
                </div>
                <div className="w-2/3 text-sm font-medium text-slate-900">
                  <span className=${`px-2 py-0.5 rounded text-[11px] font-bold text-white ${severityClass}`}>
                    ${r.metadata?.severity ?? "N/A"}
                  </span>
                </div>
              </div>
              <${DataRow} label="Priority" value=${r.metadata?.priority ?? "N/A"} />
              <${DataRow} label="Status" value=${r.metadata?.status ?? "N/A"} />
              <${DataRow} label="Reported By" value=${sys.reportedBy ?? "N/A"} />
            </div>
          </section>

          <section>
            <h2 className="text-sm font-bold bg-slate-100 px-3 py-1 mb-3 uppercase tracking-widest text-slate-700 border-l-4 border-blue-500">
              [2] Environment Context
            </h2>
            <div className="space-y-1 pl-1">
              <${DataRow} label="URL" value=${sys.url ?? "N/A"} />
              <${DataRow} label="Client" value=${r.environment?.client ?? "N/A"} />
              <${DataRow} label="Device" value=${r.environment?.device ?? "N/A"} />
              <${DataRow} label="OS/Platform" value=${r.environment?.osPlatform ?? "N/A"} />
              <${DataRow} label="Environment" value=${sys.environment ?? "N/A"} />
              <${DataRow} label="Network" value=${r.environment?.networkCondition ?? "N/A"} />
            </div>
          </section>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mb-8">
          <${StatusCard}
            title="Expected"
            content=${r.behavior?.expected ?? "N/A"}
            type="success"
          />
          <${StatusCard}
            title="Observed"
            content=${r.behavior?.observed ?? "N/A"}
            type="error"
          />
        </div>

        <section className="mb-8">
          <h2 className="text-sm font-bold bg-slate-100 px-3 py-1 mb-4 uppercase tracking-widest text-slate-700 border-l-4 border-purple-500">
            [5] Steps to Reproduce
          </h2>
          <div className="pl-4">
            ${
              (r.stepsToReproduce ?? []).length > 0
                ? (r.stepsToReproduce ?? []).map(
                    (step, index) => html`
                      <div key=${`${index}-${step}`} className="flex items-start gap-3 mb-3">
                        <span className="bg-purple-100 text-purple-700 w-6 h-6 rounded-full flex items-center justify-center font-bold text-xs shrink-0 mt-0.5">
                          ${index + 1}
                        </span>
                        <p className="text-slate-700 text-sm leading-relaxed pt-0.5">
                          ${step}
                        </p>
                      </div>
                    `
                  )
                : html`
                    <p className="text-slate-500 italic">No steps provided</p>
                  `
            }
          </div>
        </section>

        <section className="mb-8">
          <h2 className="text-sm font-bold bg-slate-100 px-3 py-1 mb-4 uppercase tracking-widest text-slate-700 border-l-4 border-slate-800">
            [6] Technical Details
          </h2>
          <div className="border border-slate-200 rounded-lg overflow-hidden">
            <div className="grid grid-cols-2 border-b border-slate-200 bg-slate-50">
              <div className="p-3 border-r border-slate-200">
                <span className="block text-[10px] font-bold text-slate-400 uppercase">
                  Error Code
                </span>
                <span className="font-mono text-sm text-red-600">
                  ${r.technicalDetails?.errorCode ?? "N/A"}
                </span>
              </div>
              <div className="p-3">
                <span className="block text-[10px] font-bold text-slate-400 uppercase">
                  Component
                </span>
                <span className="font-mono text-sm">
                  ${r.technicalDetails?.component ?? "N/A"}
                </span>
              </div>
            </div>
            <div className="p-4 bg-slate-900 text-slate-300">
              <span className="block text-[10px] font-bold text-slate-500 uppercase mb-2">
                Logs / Stack Trace
              </span>
              <pre className="font-mono text-xs whitespace-pre-wrap leading-relaxed opacity-90">
${r.technicalDetails?.logsOrStackTrace ?? "N/A"}
              </pre>
            </div>
            <div className="p-4 bg-white">
              <span className="block text-[10px] font-bold text-slate-400 uppercase mb-1">
                Additional Notes
              </span>
              <p className="text-sm text-slate-600 whitespace-pre-wrap">
                ${r.technicalDetails?.additionalNotes ?? "N/A"}
              </p>
            </div>
          </div>
        </section>

        ${
          hasImageFiles &&
          html`
            <section className="mb-8">
              <h2 className="text-sm font-bold bg-slate-100 px-3 py-1 mb-4 uppercase tracking-widest text-slate-700 border-l-4 border-cyan-500">
                [7] Attachments
              </h2>
              <div className="space-y-6">
                ${files
                  .filter((file) => file.type === "image")
                  .map(
                    (file, index) => html`
                      <div key=${file.id} className="border border-slate-200 p-2 rounded-lg bg-slate-50">
                        <img
                          src=${file.preview}
                          alt=${file.name}
                          className="w-full h-auto rounded border border-slate-200 object-contain max-h-[500px] mx-auto"
                        />
                        <p className="text-center text-xs text-slate-500 mt-2 font-mono">
                          Attachment ${index + 1}: ${file.name}
                        </p>
                      </div>
                    `
                  )}
              </div>
            </section>
          `
        }

        <section className="mb-8">
          <h2 className="text-sm font-bold bg-slate-100 px-3 py-1 mb-4 uppercase tracking-widest text-slate-700 border-l-4 border-amber-500">
            [8] Impact Analysis
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="p-4 border border-amber-100 bg-amber-50/30 rounded-lg">
              <h3 className="text-[10px] font-bold text-amber-600 uppercase mb-2 flex items-center gap-1">
                <${LucideIcon} name="users" size=${12} className="text-amber-600" />
                User Impact
              </h3>
              <p className="text-sm text-slate-700 whitespace-pre-wrap">
                ${r.impact?.user ?? "N/A"}
              </p>
            </div>
            <div className="p-4 border border-amber-100 bg-amber-50/30 rounded-lg">
              <h3 className="text-[10px] font-bold text-amber-600 uppercase mb-2 flex items-center gap-1">
                <${LucideIcon} name="target" size=${12} className="text-amber-600" />
                Business Impact
              </h3>
              <p className="text-sm text-slate-700 whitespace-pre-wrap">
                ${r.impact?.business ?? "N/A"}
              </p>
            </div>
          </div>
        </section>

        <section className="mb-8">
          <h2 className="text-sm font-bold bg-slate-100 px-3 py-1 mb-4 uppercase tracking-widest text-slate-700 border-l-4 border-pink-500">
            [9] Investigation Notes (Internal)
          </h2>
          <div className="space-y-3 pl-1">
            <div>
              <strong className="text-xs uppercase text-slate-500 mr-2 block mb-1">
                Root Cause:
              </strong>
              <p className="text-sm text-slate-800 bg-slate-50 p-2 rounded border border-slate-100 whitespace-pre-wrap">
                ${r.investigation?.rootCause ?? "N/A"}
              </p>
            </div>
            <div>
              <strong className="text-xs uppercase text-slate-500 mr-2 block mb-1">
                Workaround:
              </strong>
              <p className="text-sm text-slate-800 bg-slate-50 p-2 rounded border border-slate-100 whitespace-pre-wrap">
                ${r.investigation?.workaround ?? "N/A"}
              </p>
            </div>
            <div>
              <strong className="text-xs uppercase text-slate-500 mr-2 block mb-1">
                Proposed Fix:
              </strong>
              <p className="text-sm text-slate-800 bg-slate-50 p-2 rounded border border-slate-100 whitespace-pre-wrap">
                ${r.investigation?.proposedFix ?? "N/A"}
              </p>
            </div>
          </div>
        </section>

        <section className="mb-4">
          <h2 className="text-sm font-bold bg-slate-100 px-3 py-1 mb-4 uppercase tracking-widest text-slate-700 border-l-4 border-teal-500">
            [10] Resolution Details
          </h2>
          <div className="bg-slate-50 border border-slate-200 rounded-lg p-4 grid grid-cols-2 md:grid-cols-4 gap-4">
            <div>
              <span className="block text-[10px] uppercase font-bold text-slate-400 mb-1">
                Resolved By
              </span>
              <span className="text-sm font-medium text-slate-500 italic">
                N/A (Pending)
              </span>
            </div>
            <div>
              <span className="block text-[10px] uppercase font-bold text-slate-400 mb-1">
                Date
              </span>
              <span className="text-sm font-medium text-slate-500 italic">
                N/A (Pending)
              </span>
            </div>
            <div>
              <span className="block text-[10px] uppercase font-bold text-slate-400 mb-1">
                Fix Version
              </span>
              <span className="text-sm font-medium text-slate-500 italic">
                N/A (Pending)
              </span>
            </div>
            <div>
              <span className="block text-[10px] uppercase font-bold text-slate-400 mb-1">
                Verification
              </span>
              <span className="text-sm font-medium text-slate-500 italic">
                N/A (Pending)
              </span>
            </div>
          </div>
        </section>

        <div className="mt-12 text-center text-xs font-bold text-slate-300 uppercase tracking-widest border-t border-slate-100 pt-8">
          End of Report
        </div>
      </div>
    `;
  };

  const LoadingDots = () => {
    const [index, setIndex] = React.useState(0);
    const sequence = ["", ".", "..", "...", "..", "."];

    React.useEffect(() => {
      const interval = setInterval(() => {
        setIndex((prev) => (prev + 1) % sequence.length);
      }, 400);
      return () => clearInterval(interval);
    }, []);

    return sequence[index];
  };

  window.BugGenie.components = {
    LucideIcon,
    InputGroup,
    StatusCard,
    DataRow,
    ErrorBoundary,
    ReportDisplay,
    LoadingDots
  };
})();
